//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uargaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аварийная_работа
    {
        public int Код { get; set; }
        public string Повреждение { get; set; }
        public string Характер_повреждения { get; set; }
        public string Объект { get; set; }
        public string Связь { get; set; }
        public Nullable<System.DateTime> Время_начала { get; set; }
        public Nullable<System.DateTime> Время_конца { get; set; }
        public Nullable<bool> Статус { get; set; }
        public string Примечание { get; set; }
        public Nullable<int> Код_Заявки { get; set; }
        public Nullable<int> Код_Участка { get; set; }
        public Nullable<int> Код_Материалов { get; set; }
        public Nullable<int> Код_Бригады { get; set; }
    
        public virtual Заявка Заявка { get; set; }
        public virtual Список_использованных_материалов Список_использованных_материалов { get; set; }
        public virtual Участок Участок { get; set; }
        public virtual Бригада Бригада { get; set; }
    }
}
