//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uargaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бригада
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Бригада()
        {
            this.Аварийная_работа = new HashSet<Аварийная_работа>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Количество_сотрудников { get; set; }
        public Nullable<int> Код_Смены { get; set; }
        public Nullable<int> Код_Сотрудников { get; set; }
        public Nullable<int> Код_Транспорта { get; set; }
    
        public virtual Смена Смена { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Транспорт Транспорт { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Аварийная_работа> Аварийная_работа { get; set; }
    }
}
